apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: concourse-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: concourse-web
    spec:
      containers:
      - name: concourse-web
        args:
        - web
        - --postgres-data-source=postgres://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@concourse-postgresql:5432/concourse?sslmode=disable
        image: concourse/concourse
        env:
        - name: CONCOURSE_BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: concourse-secrets
              key: basic-auth-username
        - name: CONCOURSE_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-secrets
              key: basic-auth-password
        - name: CONCOURSE_SESSION_SIGNING_KEY
          value: /etc/secrets/concourse/session-signing-key
        - name: CONCOURSE_TSA_HOST_KEY
          value: /etc/secrets/concourse/tsa-host-private-key
        - name: CONCOURSE_TSA_AUTHORIZED_KEYS
          value: /etc/secrets/concourse/tsa-authorized-keys
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: concourse-postgresql-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-postgresql-secrets
              key: password
        - name: EXTERNAL_URL
          value: http://concourse-web:8080
        - name: MY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PEER_URL
          value: http://$(MY_IP):8080
        ports:
        - containerPort: 8080
          name: atc
        - containerPort: 2222
          name: tsa
        volumeMounts:
        - name: concourse-secrets
          mountPath: /etc/secrets/concourse
          readOnly: true
      volumes:
      - name: concourse-secrets
        secret:
          secretName: concourse-secrets
